name: lucumaa_glass_erp
description: ERP Mobile App for Lucumaa Glass
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0

  formz: ^0.7.0
  connectivity_plus: ^6.1.3
  local_auth: ^2.2.0

  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.3
  logger: ^2.5.0
  intl: ^0.20.2

  shimmer: ^3.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5

  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1

  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^3.2.2
  hive: ^2.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true
